source "https://rubygems.org"

gem "kramdown"
gem "kramdown-parser-gfm"
gem "rouge"
gem "jekyll"
gem "jekyll-paginate"
gem "jekyll-paginate-content"
gem "json"
gem "logger"
gem "base64"
gem "bigdecimal"
