name: Kirill Markin | Portfolio
title: Kirill Markin | Portfolio
description: Kirill Markin\'s Portfolio
tags:
  - C++
  - DirectX 12
  - Unreal Engine
  - Gamedev
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: kmarkindev@gmail.com
# See: https://disqus.com/
disqus_username:
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id:
